# **** Game ****
BOARD_SIZE = 6
MAXIMUM_ACTION = BOARD_SIZE * BOARD_SIZE
PATH = str(BOARD_SIZE) + "x" + str(BOARD_SIZE)

# **** Model ****
BATCH_SIZE = 64
EPOCHS = 2
LEARNING_RATE = 0.01
MOMENTUM = 0.9
CHANNELS = 3
BLOCKS = 12
FILTERS = 256
TEST_DATA_NUM = 1000
DEVICE = None

# **** MonteCarlo ****
SEARCH_NUM = 200
C = 1
RANDOM_CHOICE = 6
TEMP = 0.05

# **** SelfPlay ****
RANDOM_PLAY_NUM = 800
GENERATE_NUM = 800
